### ISSUE TITLE
DeviceBuilder_IotivityLiteServer.sh results in the following error:

### ISSUE THREAD

**Issue by ansee7221** [openconnectivityfoundation/DeviceBuilder#22]
@WAvdBeek  , Hi

<Development Environment>
Linux : ubuntu 20.4

Running DeviceBuilder_IotivityLiteServer.sh  results in the following error:
For your information, I downloaded it from "github" and didn't modify the source code at all.

~/iot-lite/DeviceBuilder# sh DeviceBuilder_IotivityLiteServer.sh ./test/input_DeviceBuilderInputFormat/input-lightdevice.json  ../lightdevice "oic.d.light"
~
remove_query_param
   href: /binaryswitch  query name: None
Traceback (most recent call last):
  File "./src/DeviceBuilder.py", line 1604, in <module>
    main_app(myargs, "introspection")
  File "./src/DeviceBuilder.py", line 1527, in main_app
    create_introspection(file_data, rt_values_file, rt_values, index, str(my_args.resource_dir)+"/schemas", schema_files)
  File "./src/DeviceBuilder.py", line 1278, in create_introspection
    remove_query_param(json_data, rt_value_file, rt_single)
  File "./src/DeviceBuilder.py", line 1113, in remove_query_param
    if is_query_to_be_removed(dict_value, remove_param):
  File "./src/DeviceBuilder.py", line 1081, in is_query_to_be_removed
    if in_v == "query" and name in remove_param:
TypeError: argument of type 'NoneType' is not iterable

[iot-lite_DeviceBuilder_error.txt](https://github.com/openconnectivityfoundation/DeviceBuilder/files/5896858/iot-lite_DeviceBuilder_error.txt)

**Comment by WAvdBeek** [comment]
fixed!
https://github.com/openconnectivityfoundation/DeviceBuilder/commit/5d03c968033e0bb5647c6eb817052a4a688f44ac
